version: '3.8'
services:
  goweb-front-exercise:
    container_name: front_exercise
    build: .
    tty: true
    volumes:
      - .:/go/src
      - ./.git:/go/src/app/.git
    ports:
      - 8081:8081
    networks:
      - external
networks:
  external:
    name: goweb-exercise-net
    external: true