server:
  hostname: "service_exercise"
  port: 8085
  paths:
    category_list: "/category/list"
    product_keyword: "/product/keyword/%s"
    product_register: "/product/register"
app:
  hostname: "localhost"
  port: 8081
  group: "/exercise"
  paths:
    top: "/top"
    search: "/search"
    register: "/register"
  views:
    base: "./views"
    top: "top/top.html"
    search: "search/search.html"
    register_enter: "register/enter.html"
    register_complete: "register/complete.html"
    error: "error/error.html"